#!/bin/bash
sleep 15     
cd /home/tropic/Dropbox/TROPIQUE/pyTropique/acquisition/version1/server_kin/
xterm -hold -e "cd ~/Dropbox/TROPIQUE/pyTropique/acquisition/version1/server_kin/ && python client_kinect.py"





